/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.calculator;
import javax.swing.*;

/**
 *
 * @author janin
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */


    public NewJFrame() {
        initComponents();
        jTabbedPane1.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        simpleDigit1 = new javax.swing.JButton();
        simpleDigit2 = new javax.swing.JButton();
        simpleDigit3 = new javax.swing.JButton();
        simpleDigit4 = new javax.swing.JButton();
        simpleDigit5 = new javax.swing.JButton();
        simpleDigit6 = new javax.swing.JButton();
        simpleDigit7 = new javax.swing.JButton();
        simpleDigit8 = new javax.swing.JButton();
        simpleDigit9 = new javax.swing.JButton();
        simpleDigit0 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        displayMem = new javax.swing.JButton();
        addMem = new javax.swing.JButton();
        subMem = new javax.swing.JButton();
        memClear = new javax.swing.JButton();
        clearText = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        proDigit0 = new javax.swing.JButton();
        proDigit1 = new javax.swing.JButton();
        proDigit3 = new javax.swing.JButton();
        proDigit2 = new javax.swing.JButton();
        proDigit4 = new javax.swing.JButton();
        proDigit5 = new javax.swing.JButton();
        proDigit6 = new javax.swing.JButton();
        proDigit7 = new javax.swing.JButton();
        proDigit8 = new javax.swing.JButton();
        proDigit9 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        Binary = new javax.swing.JButton();
        octal = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        hexaDecimal = new javax.swing.JButton();
        proEqual = new javax.swing.JButton();
        proClear = new javax.swing.JButton();
        proMul = new javax.swing.JButton();
        proAdd = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setText("jButton1");

        jButton5.setText("jButton3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Simple Calculator");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Programme Calculator");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Menu Bar");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton2)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 487));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Simple Calculator");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        simpleDigit1.setText("1");
        simpleDigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleDigit1ActionPerformed(evt);
            }
        });

        simpleDigit2.setText("2");
        simpleDigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleDigit2ActionPerformed(evt);
            }
        });

        simpleDigit3.setText("3");
        simpleDigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleDigit3ActionPerformed(evt);
            }
        });

        simpleDigit4.setText("4");
        simpleDigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleDigit4ActionPerformed(evt);
            }
        });

        simpleDigit5.setText("5");
        simpleDigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleDigit5ActionPerformed(evt);
            }
        });

        simpleDigit6.setText("6");
        simpleDigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleDigit6ActionPerformed(evt);
            }
        });

        simpleDigit7.setText("7");
        simpleDigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleDigit7ActionPerformed(evt);
            }
        });

        simpleDigit8.setText("8");
        simpleDigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleDigit8ActionPerformed(evt);
            }
        });

        simpleDigit9.setText("9");
        simpleDigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleDigit9ActionPerformed(evt);
            }
        });

        simpleDigit0.setText("0");
        simpleDigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleDigit0ActionPerformed(evt);
            }
        });

        add.setText("+");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        sub.setText("-");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        mul.setText("X");
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        displayMem.setText("M");
        displayMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayMemActionPerformed(evt);
            }
        });

        addMem.setText("M+");
        addMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemActionPerformed(evt);
            }
        });

        subMem.setText("M-");
        subMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMemActionPerformed(evt);
            }
        });

        memClear.setText("MC");
        memClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memClearActionPerformed(evt);
            }
        });

        clearText.setText("CL");
        clearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTextActionPerformed(evt);
            }
        });

        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(simpleDigit6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpleDigit7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpleDigit8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpleDigit9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpleDigit0))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addComponent(addMem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(memClear)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(displayMem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(subMem))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(divide)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(add)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sub)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mul)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(equal)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addComponent(simpleDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(simpleDigit2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(simpleDigit3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(simpleDigit4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(simpleDigit5)))
                        .addGap(32, 32, 32)
                        .addComponent(clearText)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {add, addMem, clearText, displayMem, divide, equal, memClear, mul, simpleDigit0, simpleDigit1, simpleDigit2, simpleDigit3, simpleDigit4, simpleDigit5, simpleDigit6, simpleDigit7, simpleDigit8, simpleDigit9, sub, subMem});

        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpleDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpleDigit2)
                    .addComponent(simpleDigit3)
                    .addComponent(simpleDigit4)
                    .addComponent(simpleDigit5)
                    .addComponent(clearText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpleDigit6)
                    .addComponent(simpleDigit7)
                    .addComponent(simpleDigit8)
                    .addComponent(simpleDigit9)
                    .addComponent(simpleDigit0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divide)
                    .addComponent(add)
                    .addComponent(sub)
                    .addComponent(mul)
                    .addComponent(equal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMem)
                    .addComponent(memClear)
                    .addComponent(displayMem)
                    .addComponent(subMem))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {add, addMem, clearText, displayMem, divide, equal, memClear, mul, simpleDigit0, simpleDigit1, simpleDigit2, simpleDigit3, simpleDigit4, simpleDigit5, simpleDigit6, simpleDigit7, simpleDigit8, simpleDigit9, sub, subMem});

        jTabbedPane1.addTab("tab2", jPanel8);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Programming Calculator");

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        proDigit0.setText("0");
        proDigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDigit0ActionPerformed(evt);
            }
        });

        proDigit1.setText("1");
        proDigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDigit1ActionPerformed(evt);
            }
        });

        proDigit3.setText("3");
        proDigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDigit3ActionPerformed(evt);
            }
        });

        proDigit2.setText("2");
        proDigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDigit2ActionPerformed(evt);
            }
        });

        proDigit4.setText("4");
        proDigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDigit4ActionPerformed(evt);
            }
        });

        proDigit5.setText("5");
        proDigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDigit5ActionPerformed(evt);
            }
        });

        proDigit6.setText("6");
        proDigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDigit6ActionPerformed(evt);
            }
        });

        proDigit7.setText("7");
        proDigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDigit7ActionPerformed(evt);
            }
        });

        proDigit8.setText("8");
        proDigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDigit8ActionPerformed(evt);
            }
        });

        proDigit9.setText("9");
        proDigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDigit9ActionPerformed(evt);
            }
        });

        jButton15.setText("A");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("B");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("C");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("D");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("E");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("F");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        Binary.setText("Binary");
        Binary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinaryActionPerformed(evt);
            }
        });

        octal.setText("Octal");
        octal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octalActionPerformed(evt);
            }
        });

        decimal.setText("Decimal");
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });

        hexaDecimal.setText("Hexadecimal");
        hexaDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexaDecimalActionPerformed(evt);
            }
        });

        proEqual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        proEqual.setText("=");
        proEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proEqualActionPerformed(evt);
            }
        });

        proClear.setText("CLEAR");
        proClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proClearActionPerformed(evt);
            }
        });

        proMul.setText("X");
        proMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proMulActionPerformed(evt);
            }
        });

        proAdd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        proAdd.setText("+");
        proAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Binary, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(octal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hexaDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(proDigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(proDigit6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(proDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(proDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel7Layout.createSequentialGroup()
                                        .addComponent(proDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(proDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel7Layout.createSequentialGroup()
                                        .addComponent(proDigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(proDigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(proDigit9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(proDigit4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proEqual, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(proClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(proMul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Binary, decimal, hexaDecimal, jButton15, jButton16, jButton17, jButton18, jButton19, jButton20, octal, proDigit0, proDigit1, proDigit2, proDigit3, proDigit4, proDigit5, proDigit6, proDigit7, proDigit8, proDigit9});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proDigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proDigit6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proDigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proDigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proDigit9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Binary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(octal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hexaDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proMul, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Binary, decimal, hexaDecimal, jButton15, jButton16, jButton17, jButton18, jButton19, jButton20, octal, proDigit0, proDigit1, proDigit2, proDigit3, proDigit4, proDigit5, proDigit6, proDigit7, proDigit8, proDigit9});

        jTabbedPane1.addTab("tab1", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -40, 560, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double EnterNumber1;
    double EnterNumber2;
    String op;
    Double result;
    Double memory = null;
    
    
    private void EnterNumbers(String q)
    {
        String Nums = jTextField1.getText()+q;
        jTextField1.setText(Nums);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void simpleDigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleDigit1ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("1");
        
    }//GEN-LAST:event_simpleDigit1ActionPerformed

    private void simpleDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleDigit2ActionPerformed
EnterNumbers("2");        // TODO add your handling code here:
    }//GEN-LAST:event_simpleDigit2ActionPerformed

    private void simpleDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleDigit3ActionPerformed
EnterNumbers("3");        // TODO add your handling code here:
    }//GEN-LAST:event_simpleDigit3ActionPerformed

    private void simpleDigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleDigit4ActionPerformed
EnterNumbers("4");        // TODO add your handling code here:
    }//GEN-LAST:event_simpleDigit4ActionPerformed

    private void simpleDigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleDigit5ActionPerformed
EnterNumbers("5");        // TODO add your handling code here:
    }//GEN-LAST:event_simpleDigit5ActionPerformed

    private void simpleDigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleDigit6ActionPerformed
EnterNumbers("6");        // TODO add your handling code here:
    }//GEN-LAST:event_simpleDigit6ActionPerformed

    private void simpleDigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleDigit7ActionPerformed
EnterNumbers("7");        // TODO add your handling code here:
    }//GEN-LAST:event_simpleDigit7ActionPerformed

    private void simpleDigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleDigit8ActionPerformed
EnterNumbers("8");        // TODO add your handling code here:
    }//GEN-LAST:event_simpleDigit8ActionPerformed

    private void simpleDigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleDigit9ActionPerformed
 EnterNumbers("9");       // TODO add your handling code here:
    }//GEN-LAST:event_simpleDigit9ActionPerformed

    private void simpleDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleDigit0ActionPerformed
EnterNumbers("0");        // TODO add your handling code here:
    }//GEN-LAST:event_simpleDigit0ActionPerformed

    private void clearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTextActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_clearTextActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
        EnterNumber1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        op = "/";
    }//GEN-LAST:event_divideActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        EnterNumber1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        op = "+";
    }//GEN-LAST:event_addActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
        EnterNumber1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        op = "-";
    }//GEN-LAST:event_subActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
        // TODO add your handling code here:
        EnterNumber1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        op = "*";
    }//GEN-LAST:event_mulActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
        EnterNumber2 = Double.parseDouble(jTextField1.getText());
            switch (op) {
        case "+":
            result = EnterNumber1 + EnterNumber2;
           
            break;
        case "-":
            result = EnterNumber1 - EnterNumber2;
            break;
        case "*":
            result = EnterNumber1 * EnterNumber2;
            break;
        case "/":
            if (EnterNumber2 != 0) {
                result = EnterNumber1 / EnterNumber2;
            } else {
                jTextField1.setText("Error: Division by zero");
                return; // Stop further execution if division by zero
            }
            break;
        default:
            jTextField1.setText("Error: Invalid operation");
            return;
    }
            jTextField1.setText(String.valueOf(result));
        
    }//GEN-LAST:event_equalActionPerformed

    private void addMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemActionPerformed
        // TODO add your handling code here:
       
        if(memory==null){
           memory = 0.0;
           memory = memory + Double.parseDouble(jTextField1.getText());
        }
        else{
            memory = memory + Double.parseDouble(jTextField1.getText());
        }
            
            
            jTextField1.setText("");
            
        

    }//GEN-LAST:event_addMemActionPerformed

    private void displayMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayMemActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(String.valueOf(memory));
        
    }//GEN-LAST:event_displayMemActionPerformed

    private void memClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memClearActionPerformed
        // TODO add your handling code here:
        memory =null;
    }//GEN-LAST:event_memClearActionPerformed

    private void subMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMemActionPerformed
        // TODO add your handling code here:
        if(memory==null){
           jTextField1.setText("null");
        }
        else{
        memory = memory - Double.parseDouble(jTextField1.getText());
        }
        jTextField1.setText("");
    }//GEN-LAST:event_subMemActionPerformed

    private void EnterPro(String q)
    {
        String Nums = jTextField4.getText()+q;
        jTextField4.setText(Nums);
    }
    
    double EnterProNumber1;
    double EnterProNumber2;
    String proOp;
    Double proResult;
    
    
    private void proDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDigit0ActionPerformed
EnterPro("0");        // TODO add your handling code here:
    }//GEN-LAST:event_proDigit0ActionPerformed

    private void proAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proAddActionPerformed
        // TODO add your handling code here:
        EnterProNumber1 = Double.parseDouble(jTextField4.getText());
        jTextField4.setText("");
        proOp = "+";

    }//GEN-LAST:event_proAddActionPerformed

    private void proDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDigit2ActionPerformed
EnterPro("2");            // TODO add your handling code here:
    }//GEN-LAST:event_proDigit2ActionPerformed

    private void proDigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDigit1ActionPerformed
EnterPro("1");            // TODO add your handling code here:
    }//GEN-LAST:event_proDigit1ActionPerformed

    private void proDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDigit3ActionPerformed
EnterPro("3");            // TODO add your handling code here:
    }//GEN-LAST:event_proDigit3ActionPerformed

    private void proDigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDigit4ActionPerformed
EnterPro("4");            // TODO add your handling code here:
    }//GEN-LAST:event_proDigit4ActionPerformed

    private void proDigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDigit5ActionPerformed
EnterPro("5");            // TODO add your handling code here:
    }//GEN-LAST:event_proDigit5ActionPerformed

    private void proDigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDigit6ActionPerformed
EnterPro("6");            // TODO add your handling code here:
    }//GEN-LAST:event_proDigit6ActionPerformed

    private void proDigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDigit7ActionPerformed
EnterPro("7");            // TODO add your handling code here:
    }//GEN-LAST:event_proDigit7ActionPerformed

    private void proDigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDigit8ActionPerformed
EnterPro("8");            // TODO add your handling code here:
    }//GEN-LAST:event_proDigit8ActionPerformed

    private void proDigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDigit9ActionPerformed
EnterPro("9");            // TODO add your handling code here:
    }//GEN-LAST:event_proDigit9ActionPerformed

    private void proClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proClearActionPerformed
        // TODO add your handling code here:
        jTextField4.setText("");
        
    }//GEN-LAST:event_proClearActionPerformed

    private void BinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinaryActionPerformed
        // TODO add your handling code here:
        int n;
        
        n = Integer.parseInt(jTextField4.getText());
        String ans = Integer.toString(n, 2);
        jTextField4.setText(ans);
        
        
    }//GEN-LAST:event_BinaryActionPerformed

    private void octalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octalActionPerformed
        // TODO add your handling code here:
        int n;
        
        n = Integer.parseInt(jTextField4.getText());
        String ans = Integer.toString(n, 8);
        jTextField4.setText(ans);
       
    }//GEN-LAST:event_octalActionPerformed

    private void hexaDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexaDecimalActionPerformed
        // TODO add your handling code here:
        int n;
        
        n = Integer.parseInt(jTextField4.getText());
        String ans = Integer.toString(n, 16);
        jTextField4.setText(ans.toUpperCase());
    }//GEN-LAST:event_hexaDecimalActionPerformed

    private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
        // TODO add your handling code here:
        String input1 = jTextField4.getText();
        int n;
        n= convertToDecimal(input1);
        jTextField4.setText(String.valueOf(n));
    }//GEN-LAST:event_decimalActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
EnterPro("A");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
EnterPro("B");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
EnterPro("C");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
EnterPro("D");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
EnterPro("E");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
EnterPro("F");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void proMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proMulActionPerformed
        // TODO add your handling code here:
        EnterProNumber1 = Double.parseDouble(jTextField4.getText());
        jTextField4.setText("");
        proOp = "*";
        
    }//GEN-LAST:event_proMulActionPerformed

    private void proEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proEqualActionPerformed
         // Retrieve the second number input
    String input2 = jTextField4.getText();  // Second number

    // Convert the second input to decimal
    double decimalValue2 = convertToDecimal(input2);  // Adjusted to double

    double result; // Variable to store the result

    // Check the operation and perform the corresponding calculation
    switch (proOp) {
        case "+":
            result = EnterProNumber1 + decimalValue2;  // Addition
            break;
        case "-":
            result = EnterProNumber1 - decimalValue2;  // Subtraction
            break;
        case "*":
            result = EnterProNumber1 * decimalValue2;  // Multiplication
            break;
        case "/":
            if (decimalValue2 != 0) {  // Division by zero check
                result = EnterProNumber1 / decimalValue2;  // Division
            } else {
                jTextField4.setText("Error: Division by zero");
                return; // Stop further execution if division by zero
            }
            break;
        default:
            jTextField4.setText("Error: Invalid operation");
            return;  // Stop execution if the operation is invalid
    }

    // Display the result in jTextField4
    jTextField4.setText(String.valueOf(result));

    }//GEN-LAST:event_proEqualActionPerformed

    
    

    private int convertToDecimal(String input) {
    // Remove leading/trailing spaces
    input = input.trim();

    // Determine the base and convert to decimal
    if (input.matches("[01]+")) { // Binary
        return Integer.parseInt(input, 2);
    } else if (input.matches("[0-7]+")) { // Octal
        return Integer.parseInt(input, 8);
    } else if (input.matches("[0-9A-Fa-f]+")) { // Hexadecimal
        return Integer.parseInt(input, 16);
    } else { // Decimal (default)
        return Integer.parseInt(input); // Assumed to be in decimal format
    }
}
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Binary;
    private javax.swing.JButton add;
    private javax.swing.JButton addMem;
    private javax.swing.JButton clearText;
    private javax.swing.JButton decimal;
    private javax.swing.JButton displayMem;
    private javax.swing.JButton divide;
    private javax.swing.JButton equal;
    private javax.swing.JButton hexaDecimal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton memClear;
    private javax.swing.JButton mul;
    private javax.swing.JButton octal;
    private javax.swing.JButton proAdd;
    private javax.swing.JButton proClear;
    private javax.swing.JButton proDigit0;
    private javax.swing.JButton proDigit1;
    private javax.swing.JButton proDigit2;
    private javax.swing.JButton proDigit3;
    private javax.swing.JButton proDigit4;
    private javax.swing.JButton proDigit5;
    private javax.swing.JButton proDigit6;
    private javax.swing.JButton proDigit7;
    private javax.swing.JButton proDigit8;
    private javax.swing.JButton proDigit9;
    private javax.swing.JButton proEqual;
    private javax.swing.JButton proMul;
    private javax.swing.JButton simpleDigit0;
    private javax.swing.JButton simpleDigit1;
    private javax.swing.JButton simpleDigit2;
    private javax.swing.JButton simpleDigit3;
    private javax.swing.JButton simpleDigit4;
    private javax.swing.JButton simpleDigit5;
    private javax.swing.JButton simpleDigit6;
    private javax.swing.JButton simpleDigit7;
    private javax.swing.JButton simpleDigit8;
    private javax.swing.JButton simpleDigit9;
    private javax.swing.JButton sub;
    private javax.swing.JButton subMem;
    // End of variables declaration//GEN-END:variables
}
